# Generated by Django 2.2.4 on 2021-12-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tarea', models.CharField(max_length=30)),
                ('fecha_c_tarea', models.DateField(auto_now=True)),
                ('fecha_entrega', models.DateField()),
                ('especificacion', models.CharField(max_length=50, null=True)),
                ('tarea_relacion', models.CharField(max_length=30, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Crear tarea',
                'verbose_name_plural': 'Crear tareas',
            },
        ),
    ]
