# Generated by Django 2.2.4 on 2021-12-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crear_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_tarea',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Usuario', to_field='id_user'),
        ),
    ]
