# Generated by Django 2.2.4 on 2021-12-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crear_tareas', '0002_auto_20211206_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_tarea',
            old_name='nom_tarea',
            new_name='nombre_de_la_tarea',
        ),
    ]
