# Generated by Django 2.2.4 on 2021-12-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_tareas', '0003_auto_20211206_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_tarea',
            name='especificacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
