# Generated by Django 2.2.4 on 2021-12-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=30, unique=True, verbose_name='Nombre de Usuario')),
                ('correo', models.EmailField(max_length=30, unique=True, verbose_name='Correo Electronico ')),
                ('nombres', models.CharField(max_length=30, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, null=True, verbose_name='Apellidos')),
                ('user_funcionario', models.BooleanField(default=True)),
                ('user_administrador', models.BooleanField(default=False)),
                ('user_modelador', models.BooleanField(default=False)),
            ],
        ),
    ]
