# Generated by Django 2.2.4 on 2021-12-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_user',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nom_user',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_administrador',
            new_name='usuario_administrador',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_funcionario',
            new_name='usuario_funcionario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_modelador',
            new_name='usuario_modelador',
        ),
    ]
