# Generated by Django 2.2.4 on 2021-12-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0002_auto_20211206_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_modelador',
            new_name='usuario_diseñador_procesos',
        ),
    ]
