# Generated by Django 2.2.4 on 2021-12-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0003_auto_20211206_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
