# Generated by Django 2.2.4 on 2021-12-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(max_length=30)),
                ('fecha_entrega', models.DateField()),
                ('especificacion', models.CharField(max_length=100, null=True)),
                ('tarea_relacion', models.CharField(max_length=30, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Usuario')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
